num_epochs: 200
data_dir: dataset/full
model_path: ckpts/ccot-length15-59.pth
max_eval_steps: 20
per_device_train_batch_size: 64
per_device_eval_batch_size: 64
gradient_accumulation_steps: 1
num_range: 59