num_epochs: 200
model: CoT
model_config: config/models/CoT-config-default.json
model_path: models/2025-03-01-09:38/model-0.pth
eval_max_steps: 20
data_dir: dataset/full
per_device_train_batch_size: 96
per_device_eval_batch_size: 96
gradient_accumulation_steps: 1
num_range: 59