num_epochs: 200
model: CoT
model_config: config/models/CoT-config-default.json
model_path: ckpts/cot-length15-59.pth
max_eval_steps: 5
data_dir: dataset/full
per_device_train_batch_size: 96
per_device_eval_batch_size: 96
gradient_accumulation_steps: 1
num_range: 59